# Generated by Django 3.2 on 2021-05-03 06:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PikifyUser',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('firstName', models.TextField(default='')),
                ('lastName', models.TextField(default='')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('displayName', models.TextField(default='')),
                ('password', models.TextField(default='')),
                ('profileImageUrl', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('url', models.TextField(default='')),
                ('private', models.BooleanField(default='')),
                ('userId', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pikify.pikifyuser')),
            ],
        ),
    ]
