# Generated by Django 3.2 on 2021-05-03 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pikify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='userId',
            new_name='user',
        ),
    ]
