# Generated by Django 3.2 on 2021-05-05 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pikify', '0002_rename_userid_image_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pikifyuser',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='pikifyuser',
            name='displayName',
        ),
        migrations.RemoveField(
            model_name='pikifyuser',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='pikifyuser',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='pikifyuser',
            name='password',
        ),
        migrations.AddField(
            model_name='pikifyuser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pikifyuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
